### ISSUE TITLE
Strange behavior when using with other BT peripherals

### ISSUE THREAD

**Issue by jhoughjr** [FeitianSmartcardReader/bR301_iOS_SDK_RELEASE#1]
We are using the br301 as well as a StarIO bluetooth printer.
If the printer is powered off, and disconnects, the br301 goes into an unusable state until power cycled.
The strange thing is that according to the OS, it never disconnects from bluetooth so I'm guessing it is somewhere in the internals of the br301 library.

I've tried detecting the printer disconnecting and  resetting the interface, but it doesn't work reliably.
Any help would be appreciated, especially documentation on the functions in the library.
The manual from Feitian doesn't refer to any of the methods used in the latest library that I can see.

**Comment by jhoughjr** [comment]
Also, where can i download the 2.0 firmware? The link on the website is broken, as is all search functionality.

**Comment by FeitianSmartcardReader** [comment]
@jhoughjr You can find firmware from https://github.com/FeitianSmartcardReader/bR301_Windows/tree/master/Tools/Update%20Tool

May I know your bluetooth printer bluetooth version and Type? you can using debug source code to do debug, https://github.com/FeitianSmartcardReader/bR301_iOS

**Comment by FeitianSmartcardReader** [comment]
@jhoughjr Today we did test with bluetooth printer with our bR301, all it works well. We are using C90-i Bluetooth smart printer which is our local brand. Thanks,

**Comment by jhoughjr** [comment]
We are using a StarIO TSP650II with their StarIO SDK v5.0.2.
It is quite strange behavior. When the printer is powered off, the card reader disconnects.
For example, the lights on the bR301 show it as disconnected, though iOS still shows it connected in bluetooth settings.

I'll try updating the firmware and then try debugging into the framework to see what is happening.

**Comment by FeitianSmartcardReader** [comment]
Yes. Sure. Better share your debug log to me for check on our side. If the blue light turn off means the reader disconnect.
            On 12/22/2016 00:36, Jimmy Hough Jr. wrote:We are using a StarIO TSP650II with their StarIO SDK v5.0.2.
It is quite strange behavior. When the printer is powered off, the card reader disconnects.
For example, the lights on the bR301 show it as disconnected, though iOS still shows it connected in bluetooth settings.
I'll try updating the firmware and then try debugging into the framework to see what is happening.

**Comment by jhoughjr** [comment]
I'm not sure what my current debug logs would show as it does not show the callbacks being called when the reader stops responding. 

A cooped for the debug version of the framework, that would allow debugging into the framework would help to see what is going on. I suspect it is in handling the EAAccessoryManager callbacks in the framework, but since that is all private, I can't diagnose anything.

**Comment by jhoughjr** [comment]
2016-12-23 15:32:59.457005 XXXX[2794:925500] [DYMTLInitPlatform] platform initialization successful
2016-12-23 15:32:59.978364 XXXX[2794:925528] Dec 23, 2016, 3:32:59 PM CST | DEBUG | Reader attached
2016-12-23 15:32:59.981503 XXXX[2794:925528] Dec 23, 2016, 3:32:59 PM CST | DEBUG | APN Permissions granted
2016-12-23 15:33:00.192060 XXXX[2794:925527] Dec 23, 2016, 3:33:00 PM CST | DEBUG | Reader attached
2016-12-23 15:33:00.262640 XXXX[2794:925527] Dec 23, 2016, 3:33:00 PM CST | DEBUG | APN registration succeeded. Token: A4F5E5A5E24CEAE9865360F7237500AEEFD985F7BBBBBA87E04EE2B6255052FE
2016-12-23 15:33:00.263024 XXXX[2794:925527] Dec 23, 2016, 3:33:00 PM CST | DEBUG | Refreshing printer status
SUCCESS: {
    status = OK;
}
2016-12-23 15:33:18.386191 XXXX[2794:925585] Dec 23, 2016, 3:33:18 PM CST | DEBUG | Card detached.
2016-12-23 15:33:19.810835 XXXX[2794:925528] Dec 23, 2016, 3:33:19 PM CST | DEBUG | Card attached.

// here i switch the printer off.
// removing and inserting the card does nothing
// I then power off the bR301 and power it back on with a card in it.
2016-12-23 15:33:58.927559 XXXX[2794:925723] Dec 23, 2016, 3:33:58 PM CST | DEBUG | Reader detached
// power on reader
2016-12-23 15:34:11.719949 XXXX[2794:925489] Dec 23, 2016, 3:34:11 PM CST | DEBUG | Reader attached
2016-12-23 15:34:16.958834 XXXX[2794:925795] Dec 23, 2016, 3:34:16 PM CST | DEBUG | Card detached.

// card is in but says detached, so i reinsert it.
2016-12-23 15:34:18.379276 XXXX[2794:925489] Dec 23, 2016, 3:34:18 PM CST | DEBUG | Card attached.

**Comment by FeitianSmartcardReader** [comment]
@jhoughjr was on holiday, just back to this issue, let me check and back to you later, thanks

**Comment by FeitianSmartcardReader** [comment]
@jhoughjr please using our debug lib to do build and get log for check, using https://github.com/FeitianSmartcardReader/bR301_SDK_Latest/blob/master/SDK/iOS/Lib/lib/libiRockey301_ccid_V1.31.5_debug.a. and on other hand, is possible to have remote session? I contact our R&D to see what happens, looking forward to your reply, thanks

**Comment by jhoughjr** [comment]
I would have to check with my employer about a remote session to make sure it is authorized since I am under an NDA. 

There is really nothing to see debug wise. It outputs nothing.
This problem has existed before I started on the project in a previous version of the app.
I've been told other peripherals interact with the card reader also.

I'll let you know asap about the remote session. Many people at the office are still out, so I'll have to wait until they are back.

**Comment by FeitianSmartcardReader** [comment]
The issue was solved in 1.31.7, close
