### ISSUE TITLE
bR301 Android SDK: NullpointerException when turning off reader

### ISSUE THREAD

**Issue by hoschbel** [FeitianSmartcardReader/bR301_iOS_SDK_RELEASE#3]
The reader is working quite good with the Android SDK. But one thing needs to be fixed:
When turning off the reader (pressing the power button for several seconds) the Android application crashes with NullpointerException at com.feitian.readerdk.deviceconnect.AndroidBlueToothDeviceConnect$ReadThread.run(AndroidBlueToothDeviceConnect.java:277)

Line 277 is:
AndroidBlueToothDeviceConnect.this.mHandle.obtainMessage('\ue001', '\uf003', -1).sendToTarget();

I think the app has no chance to catch this exception. So it would be nice if you could fix that.

**Comment by FeitianSmartcardReader** [comment]
Thanks for your feedback, will check and give feedback soon, thanks

**Comment by FeitianSmartcardReader** [comment]
@hoschbel  did you using our latest 2.0.5 jar do test? I did check and it works.
[log.txt](https://github.com/FeitianSmartcardReader/bR301_SDK_Latest/files/823652/log.txt)
